<a href="https://colab.research.google.com/github/Coder-twhjr/Mind-Reader-Game/blob/main/NumPy_Arrays_I.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NumPy Arrays I


####NumPy Arrays - The `ones()` & `zeros()` Functions

In [1]:
import numpy as np
ones = np.ones((5, 3, 3), dtype=int)
ones

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [2]:
type(ones)

numpy.ndarray

In [3]:
zeros = np.zeros((4, 2, 3), dtype=int)
zeros 

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]])

In [4]:
zeros_float = np.zeros((4, 2, 3))
zeros_float

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

---

####The `dtype` Keyword

In [5]:
zeros_float.dtype

dtype('float64')

In [6]:
ones.dtype

dtype('int64')

In [7]:
import random
import numpy

print(type(2020))
print(type(3.14))
print(type('Earth'))
print(type([i for i in range(1, 11)]))
print(type(numpy))
print(type(random))

<class 'int'>
<class 'float'>
<class 'str'>
<class 'list'>
<class 'module'>
<class 'module'>


---

####The `ndim` And `shape` Keywords

In [8]:
print(ones.ndim)
print(zeros.ndim)
print(zeros_float.ndim)

3
3
3


In [9]:
print(ones.shape)
print(zeros.shape)
print(zeros_float.shape)

(5, 3, 3)
(4, 2, 3)
(4, 2, 3)


---

####The `arange()` And `linspace()` Functions

In [10]:
array1 = np.arange(5, 21)
array1

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [11]:
array2 = np.arange(1, 25, 4) 
array2

array([ 1,  5,  9, 13, 17, 21])

In [12]:
array3 = np.arange(1, 25, 4, dtype=float) 
array3

array([ 1.,  5.,  9., 13., 17., 21.])

In [13]:
array4 = np.linspace(1, 25, 4)
array4

array([ 1.,  9., 17., 25.])

In [14]:
array5 = np.linspace(1, 25, 10)
array5

array([ 1.        ,  3.66666667,  6.33333333,  9.        , 11.66666667,
       14.33333333, 17.        , 19.66666667, 22.33333333, 25.        ])

---

####The `reshape()` Function

In [15]:
print(zeros)
reshaped_zeros = zeros.reshape(6, 4)
reshaped_zeros

[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]


array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [16]:
reshaped_ones = ones.reshape((45,)) # (45,) signifies that the array has just one row and 45 items.
reshaped_ones

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1])

---

####The `ndarray()` Function

In [17]:
some_array = np.ndarray((5, 2), dtype=int)
some_array

array([[4607182418800017408, 4615439018116863317],
       [4618816717837391189, 4621256167635550208],
       [4622757367511340373, 4624258567387130538],
       [4625478292286210048, 4626228892224105130],
       [4626979492162000213, 4627730092099895296]])

---

####The `random.randint()` Function

In [18]:
rand_1d_array = np.random.randint(50, 100, size=15)
rand_1d_array

array([68, 81, 73, 90, 90, 99, 56, 63, 62, 68, 75, 90, 62, 61, 70])

In [19]:
rand_2d_array = np.random.randint(50, 100, size=(5, 3))
rand_2d_array

array([[67, 87, 85],
       [96, 80, 75],
       [81, 83, 91],
       [77, 62, 81],
       [62, 80, 84]])

In [20]:
rand_3d_array = np.random.randint(10, 50, size=(4, 2, 5))
rand_3d_array

array([[[20, 10, 12, 46, 44],
        [14, 44, 45, 48, 46]],

       [[35, 21, 28, 41, 19],
        [21, 44, 28, 31, 22]],

       [[16, 23, 31, 42, 41],
        [14, 38, 49, 20, 45]],

       [[16, 22, 17, 26, 13],
        [14, 21, 11, 16, 17]]])

---

####The `array()` Function

In [21]:
arr = np.array([i for i in range(1, 16)])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [22]:
type(arr)

numpy.ndarray

---

####The `list()` Function

In [23]:
arr_converted = list(arr)

In [24]:
type(arr_converted)

list

---

####The `sqrt()` Function

In [25]:
def is_triangle(a, b, c):
  if ((a + b) > c) and ((a + c) > b) and ((b + c) > a):
    return True
  else:
    return False

is_triangle(5, 6, 7)

True

In [26]:
def heron_formula(a, b, c):
  if is_triangle(a, b, c) == True:
    s = (a + b + c) / 2
    return np.sqrt(s * (s - a) * (s - b) * (s - c))
  else:
    return "Invalid triangle."

print(heron_formula(5, 1, 7))
heron_formula(5, 6, 7)

Invalid triangle.


14.696938456699069

---

####Trigonometric, Exponential & Logarithmic Functions



In [27]:
angles = np.arange(0, 95, 15)
angles

array([ 0, 15, 30, 45, 60, 75, 90])

**The `np.sin()` Function** 

In [28]:
np.sin(np.deg2rad(angles))

array([0.        , 0.25881905, 0.5       , 0.70710678, 0.8660254 ,
       0.96592583, 1.        ])

**The `np.cos()` Function** 

In [29]:
np.cos(np.deg2rad(angles))

array([1.00000000e+00, 9.65925826e-01, 8.66025404e-01, 7.07106781e-01,
       5.00000000e-01, 2.58819045e-01, 6.12323400e-17])

**The `np.tan()` Function** 

In [30]:
np.tan(np.deg2rad(angles))

array([0.00000000e+00, 2.67949192e-01, 5.77350269e-01, 1.00000000e+00,
       1.73205081e+00, 3.73205081e+00, 1.63312394e+16])

**The `np.exp()` Function** 

In [31]:
exp = [np.exp(i) for i in range(1, 11)]
exp

[2.718281828459045,
 7.38905609893065,
 20.085536923187668,
 54.598150033144236,
 148.4131591025766,
 403.4287934927351,
 1096.6331584284585,
 2980.9579870417283,
 8103.083927575384,
 22026.465794806718]

**The `np.log()` Function** 

The default base of `np.log()` function is $e = 2.7182$ or `np.exp(1)`

In [32]:
np.log(exp)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [33]:
np.log10([10 ** i for i in range(1, 11)])

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

---

####Union & Intersection

In [34]:
array1 = np.arange(1, 11)
array2 = np.arange(6, 26)
np.intersect1d(array1, array2)

array([ 6,  7,  8,  9, 10])

In [35]:
np.union1d(array1, array2)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

---