<a href="https://colab.research.google.com/github/Coder-twhjr/Mind-Reader-Game/blob/main/NumPy_Arrays_II.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NumPy Arrays II


####Array Length



In [1]:
import numpy as np

one_dim_ar = np.arange(1, 25)
two_dim_ar = np.arange(1, 29).reshape(4, 7)
three_dim_ar = np.arange(1, 31).reshape(2, 5, 3)
print("Number of items in one_dim_ar:", len(one_dim_ar))
print("Number of rows in two_dim_ar:", len(two_dim_ar))
print("Number of blocks in three_dim_ar:", len(three_dim_ar))

Number of items in one_dim_ar: 24
Number of rows in two_dim_ar: 4
Number of blocks in three_dim_ar: 2


---

#### The `size` Keyword

In [2]:
print("Number of items in one_dim_ar:", one_dim_ar.size)
print("Number of items in two_dim_ar:", two_dim_ar.size)
print("Number of items in three_dim_ar:", three_dim_ar.size)

Number of items in one_dim_ar: 24
Number of items in two_dim_ar: 28
Number of items in three_dim_ar: 30


---

####Descriptive Statistics

In [3]:
prices = np.array([13999, 6298, 10999, 14999, 7298, 6385, 8999, 9999, 9999, 13868])
units_available = np.array([9, 8, 9, 9, 8, 8, 9, 6, 5, 7])

In [4]:
total_price_for_each_smartphone = prices * units_available
print(total_price_for_each_smartphone)

total_monetary_value = np.sum(total_price_for_each_smartphone)
total_monetary_value

[125991  50384  98991 134991  58384  51080  80991  59994  49995  97076]


807877

In [5]:
avg_price = np.mean(prices)
avg_price

10284.3

In [6]:
lowest_price = np.min(prices)
lowest_price

6298

In [7]:
highest_price = np.max(prices)
highest_price

14999

In [8]:
median_price = np.median(prices)
median_price

9999.0

In [9]:
from scipy import stats
stats.mode(prices)

ModeResult(mode=array([9999]), count=array([2]))

---

####Few More Operations On A NumPy Array

In [10]:
import random
import numpy as np

radii = [random.randint(1, 10) for i in range(20)]
print(radii)

np_radii = np.array(radii)
print(np_radii)

np_area_circles = np.pi * (np_radii ** 2)
np_area_circles

[8, 6, 2, 9, 8, 8, 10, 1, 9, 9, 7, 1, 3, 2, 10, 2, 10, 7, 9, 2]
[ 8  6  2  9  8  8 10  1  9  9  7  1  3  2 10  2 10  7  9  2]


array([201.06192983, 113.09733553,  12.56637061, 254.46900494,
       201.06192983, 201.06192983, 314.15926536,   3.14159265,
       254.46900494, 254.46900494, 153.93804003,   3.14159265,
        28.27433388,  12.56637061, 314.15926536,  12.56637061,
       314.15926536, 153.93804003, 254.46900494,  12.56637061])

In [11]:
radii ** 2

TypeError: ignored

In [12]:
3.14 * radii

TypeError: ignored

In [14]:
for radius in radii:
  print(np.pi * (radius ** 2))

201.06192982974676
113.09733552923255
12.566370614359172
254.46900494077323
201.06192982974676
201.06192982974676
314.1592653589793
3.141592653589793
254.46900494077323
254.46900494077323
153.93804002589985
3.141592653589793
28.274333882308138
12.566370614359172
314.1592653589793
12.566370614359172
314.1592653589793
153.93804002589985
254.46900494077323
12.566370614359172


In [15]:
cyl_radii = np.arange(1, 11) 
cyl_heights = np.arange(11, 21)

cyl_vol = np.pi * (cyl_radii ** 2) * cyl_heights
cyl_vol

array([  34.55751919,  150.79644737,  367.56634047,  703.7167544 ,
       1178.0972451 , 1809.55736847, 2616.94668044, 3619.11473694,
       4834.91109387, 6283.18530718])

---

####Python List And NumPy Array Performance Comparison

In [16]:
import numpy as np
import time

py_t0 = time.time() 
py_list = [i for i in range(1, 100001)]
py_t1 = time.time()
py_time_diff = (py_t1 - py_t0)
print("Time taken to create a Python list is", py_time_diff, "seconds.")

np_t0 = time.time()
np_ones = np.arange(1, 100001)

np_t1 = time.time()

np_time_diff = (np_t1 - np_t0)
print("Time taken to create a NumPy array is", np_time_diff, "seconds.")

print("A NumPy array is", py_time_diff // np_time_diff, "times faster than a Python list for the same size.")

Time taken to create a Python list is 0.014884233474731445 seconds.
Time taken to create a NumPy array is 0.00042247772216796875 seconds.
A NumPy array is 35.0 times faster than a Python list for the same size.


---

####The User-Defined `mode()` Function

In [17]:
def mode(input_array):
  counts_list = []
  input_list = list(input_array)
  for item in input_list:
    item_count = input_list.count(item)
    counts_list.append(item_count)

  counts_array = np.array(counts_list)
  max_count = np.max(counts_array)
  max_count_index = counts_list.index(max_count)
  mode = input_list[max_count_index]
  return mode, max_count

mode(prices)

(9999, 2)

---