<a href="https://colab.research.google.com/github/Coder-twhjr/Mind-Reader-Game/blob/main/Project_9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### Goal of the Project
 1. Python Lists I

 2. NumPy Arrays I

In [1]:
import numpy as np
x = np.arange(2, 11).reshape(3,3)
print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


---

In [2]:
import numpy as np
my_arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print("Original array is",my_arr)
print("Dimension is",my_arr.shape)
print("Change array shape to (3, 3) -> 3 rows and 3 columns ")
my_arr.shape = (3, 3)
print(my_arr)
converted_list=list(my_arr)
print("The data type of the converted variable is:")
type(converted_list)

Original array is [1 2 3 4 5 6 7 8 9]
Dimension is (9,)
Change array shape to (3, 3) -> 3 rows and 3 columns 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
The data type of the converted variable is:


list

---

In [3]:
import numpy as np

list1 = [4, 16, 9, 1, 25, 47]
output1 = np.sqrt(list1)
print(output1)
a=27
b=39
output2 = np.sqrt(a ** 2 + b ** 2)
print("The value of c = ", output2)

[2.        4.        3.        1.        5.        6.8556546]
The value of c =  47.43416490252569


---