<a href="https://colab.research.google.com/github/Coder-twhjr/Mind-Reader-Game/blob/main/Project_11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### Goal of the Project
  1.  Claude Shannon Algorithm I

---

In [1]:
import numpy as np

three_d_arr = np.zeros(shape=(4, 4, 4), dtype=int)
three_d_arr

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

---

In [2]:
import numpy as np

three_d_arr = np.zeros(shape=(2, 2, 2), dtype=int)
three_d_arr

array([[[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]]])

In [3]:
import random
three_d_arr[0][1][1] = random.randint(10, 50)
three_d_arr

array([[[ 0,  0],
        [ 0, 43]],

       [[ 0,  0],
        [ 0,  0]]])

In [4]:
if three_d_arr[0][1][1] > 20:
 
  three_d_arr[0][0][1] = 50
else:
  three_d_arr[0][0][1] = 20

three_d_arr

array([[[ 0, 50],
        [ 0, 43]],

       [[ 0,  0],
        [ 0,  0]]])

---